syntax = "proto3";

package auth;

service AuthService{
    rpc Login(LoginRequest) returns (LoginResponse);
    rpc DriverRegister(RegisterRequest) returns (DriverRegisterResponse);
    rpc DriverVerifyOTP(DriverVerifyOTPRequest) returns (DriverVerifyOTPResponse);
    rpc CustomerRegister(RegisterRequest) returns (RegisterResponse);
    rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse);
}

message LoginRequest{
    optional string username = 1;
    optional string email = 2;
    string password = 3;
}

message LoginResponse{
    bool is_error = 1;
    string error_code = 2;
    optional string message = 3;
    optional string access = 4;
    optional string refresh = 5;
}

enum Role{
    CUSTOMER = 0;
    DRIVER = 1;
}

message DriverRegisterResponse{
    string message = 1;
    string error_code = 2;
    bool is_error = 3;
    optional User user = 4;
    optional string token = 6;
}

message DriverVerifyOTPRequest{
    string otp = 1;
    string token = 2;
}

message DriverVerifyOTPResponse{
    optional string message = 1;
    string error_code = 2;
    bool is_error = 3;
    optional User user = 4;
    optional Driver profile = 5;
}

message RegisterRequest{
    string username = 1;
    string email = 2;
    string password = 4;
    optional Driver profile=5;
}

message User{
    string id = 1;
    string username = 2;
    string email = 3;
    Role role = 4;
}

message RegisterResponse{
    string message = 1;
    User user = 2;
    bool is_error = 3;
    string error_code = 4;
}


message RefreshTokenRequest{
    string refresh = 1;
}


message RefreshTokenResponse{
    string access = 1;
    string refresh = 2;
}



message Driver {
    string name = 1;
    string phone_number = 2;
    string license_plate = 3;
    string vehicle_type = 4;
}