syntax = "proto3";

package booking;

service BookingService {
    rpc UpdateDriverAvailability(DriverAvailabilityRequest)
        returns (DriverAvailabilityResponse);
    rpc CreateBooking(BookingRequest) returns (BookingResponse);
    rpc GetBookings(GetBookingsRequest) returns (GetBookingsResponse);
}

message GetBookingsRequest{
    int32 customer_id = 1;
    int32 page = 2;
}

message GetBookingsResponse{
    int32 page = 1;
    repeated Booking bookings = 2;
}


message BookingRequest{
    int32 customer_id = 1;
    Location pickup = 2;
    Location destination = 3;
    string vehicle_type = 4;
}


message BookingResponse{
    bool is_error = 1;  
    string error_code = 2;
    Booking booking = 3;
}

message Booking{
    int32 customer_id = 1;
    optional int32 driver_id = 2;
    Location pickup = 3;
    Location destination = 4;
    double fare = 5;
    string status = 6;
}

message DriverAvailabilityRequest {
    int32 driver_id = 1;
    string vehicle_type = 2;
    string license_plate = 3;
    string status = 4;
    Location location = 5;
}

message DriverAvailabilityResponse {
    bool is_error = 1;
    string error_code = 2;
}

message Location {
    double latitude = 1;
    double longitude = 2;
}