syntax = "proto3";

package trip;

service TripService {
    rpc CreateTrip(CreateTripRequest)
        returns (CreateTripResponse);
    rpc GetTrip(GetTripRequest)
        returns (GetTripResponse);

    rpc CancelTrip(CancelTripRequest)
        returns (CancelTripResponse);
    rpc UpdateTripStatus(UpdateTripStatusRequest)
        returns (UpdateTripStatusResponse);
}

message UpdateTripStatusRequest {
    optional int32 id = 1;
    optional string booking_id = 2;
    string status = 3;
}

message UpdateTripStatusResponse {
    bool is_error = 1;
    string error_code = 2;
    Trip trip = 3;
}

message GetTripRequest {
    optional int32 id = 1;
    optional string booking_id = 2;
}

message GetTripResponse {
    bool is_error = 1;
    string error_code = 2;
    Trip trip = 3;
}

message CancelTripRequest {
    optional string booking_id = 1;
    optional int32 id = 2;
    string cancel_reason = 3;
}

message CancelTripResponse {
    bool is_error = 1;
    string error_code = 2;
    Trip trip = 3;
}

message CreateTripRequest {
    string booking_id = 1;

    int32 customer_user_id = 2;
    int32 customer_id = 3;
    int32 driver_id = 4;

    Location pickup = 5;
    Location destination = 6;

    double fare = 7;
}

message CreateTripResponse {
    bool is_error = 1;
    string error_code = 2;
    Trip trip = 3;
}

message Trip {
    int32 id = 1;
    string booking_id = 2;

    int32 customer_user_id = 3;
    int32 customer_id = 4;
    int32 driver_id = 5;

    Location pickup = 6;
    Location destination = 7;

    double fare = 8;
    string status = 9;
}

message Location {
    double latitude = 1;
    double longitude = 2;
}